### PR TITLE
A simple convolution example to provide a proper introduction to CuPy

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
Originally, this branch was created to add some examples to chapter 02, as an assignment from the Carpentries Lesson Study Group.

It evolved into an introduction to CuPy. So it should have all the contents for chapter 02.

So what I have added is simple code to convolve a regular grid of "delta functions" with a 2D symentrical Gaussian.
First, on the CPU, using Numpy and Scipy.

Next, on the GPU, using CuPy and cupyx.

Compare the runtimes and results.

### CODE REVIEW

**Comment by psteinb** [comment]
Dear @HannoSpreeuw - apparently I oversaw this request for review. My apologies. Please let me know if I can be of help.

**Comment by HannoSpreeuw** [comment]
Okay, thanks. 
@tobyhodges is currently reviewing [episode 2](https://carpentries-incubator.github.io/lesson-gpu-programming/02-cupy/index.html) but I am happy to hear your comments as well.

**Comment by psteinb** [comment]
So, I can just create issue(s) if needed?

**Comment by HannoSpreeuw** [comment]
Please, go ahead.

**Pull request merged**
