### PR TITLE
Adding link to videos.

### PR DESCRIPTION
**Pull request by isazi**
We decided to add a couple of videos to introduce more general concepts. The videos could be pointed out to the participants in advance, or at the end of a day in multi-day courses. They could also be watched together in class if necessary.

### CODE REVIEW

**Review by HannoSpreeuw — CHANGES_REQUESTED** [review]
I was thinking that maybe this video provided a lot of information that is redundant for the course.
GDDR DRAM and voltage regulator module, for instance, seem redundant to me.

image

**Review by HannoSpreeuw — COMMENTED** [review]
This is a very nice video:
image

**Comment by HannoSpreeuw** [comment]
What is not in those two videos is the GPU programming model. So threads and blocks are mentioned, but not grids.

**Comment by isazi** [comment]
> I was thinking that maybe this video provided a lot of information that is redundant for the course. GDDR DRAM and voltage regulator module, for instance, seem redundant to me. image

It contains more than what we teach, but can be useful to more curious participants to get more info on how GPUs work.

**Comment by isazi** [comment]
> What is not in those two videos is the GPU programming model. So threads and blocks are mentioned, but not grids.

The programming model we explain ourselves

**Pull request merged**
